// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: lbsinglest.proto

package client

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in ContentMultiError, or nil if none found.
func (m *Content) ValidateAll() error {
	return m.validate(true)
}

func (m *Content) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	if all {
		switch v := interface{}(m.GetText()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Text",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Text",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetText()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Text",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetImage()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Image",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Image",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetImage()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Image",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetVideo()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Video",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Video",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVideo()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Video",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetVoice()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Voice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Voice",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetVoice()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Voice",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetDocument()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Document",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetDocument()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Document",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if all {
		switch v := interface{}(m.GetLocation()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, ContentValidationError{
					field:  "Location",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetLocation()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return ContentValidationError{
				field:  "Location",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return ContentMultiError(errors)
	}

	return nil
}

// ContentMultiError is an error wrapping multiple validation errors returned
// by Content.ValidateAll() if the designated constraints aren't met.
type ContentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ContentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ContentMultiError) AllErrors() []error { return m }

// ContentValidationError is the validation error returned by Content.Validate
// if the designated constraints aren't met.
type ContentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ContentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ContentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ContentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ContentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ContentValidationError) ErrorName() string { return "ContentValidationError" }

// Error satisfies the builtin error interface
func (e ContentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ContentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ContentValidationError{}

// Validate checks the field values on BaseUser with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *BaseUser) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on BaseUser with the rules defined in
// the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in BaseUserMultiError, or nil
// if none found.
func (m *BaseUser) ValidateAll() error {
	return m.validate(true)
}

func (m *BaseUser) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Id

	// no validation rules for Username

	// no validation rules for Avatar

	// no validation rules for Nickname

	// no validation rules for Email

	// no validation rules for Github

	// no validation rules for Desc

	// no validation rules for Role

	if len(errors) > 0 {
		return BaseUserMultiError(errors)
	}

	return nil
}

// BaseUserMultiError is an error wrapping multiple validation errors returned
// by BaseUser.ValidateAll() if the designated constraints aren't met.
type BaseUserMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m BaseUserMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m BaseUserMultiError) AllErrors() []error { return m }

// BaseUserValidationError is the validation error returned by
// BaseUser.Validate if the designated constraints aren't met.
type BaseUserValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e BaseUserValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e BaseUserValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e BaseUserValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e BaseUserValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e BaseUserValidationError) ErrorName() string { return "BaseUserValidationError" }

// Error satisfies the builtin error interface
func (e BaseUserValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sBaseUser.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = BaseUserValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = BaseUserValidationError{}

// Validate checks the field values on Login with the rules defined in the
// proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Login) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Login with the rules defined in the
// proto definition for this message. If any rules are violated, the result is
// a list of violation errors wrapped in LoginMultiError, or nil if none found.
func (m *Login) ValidateAll() error {
	return m.validate(true)
}

func (m *Login) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Sid

	// no validation rules for Uid

	if len(errors) > 0 {
		return LoginMultiError(errors)
	}

	return nil
}

// LoginMultiError is an error wrapping multiple validation errors returned by
// Login.ValidateAll() if the designated constraints aren't met.
type LoginMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LoginMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LoginMultiError) AllErrors() []error { return m }

// LoginValidationError is the validation error returned by Login.Validate if
// the designated constraints aren't met.
type LoginValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LoginValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LoginValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LoginValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LoginValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LoginValidationError) ErrorName() string { return "LoginValidationError" }

// Error satisfies the builtin error interface
func (e LoginValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLogin.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LoginValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LoginValidationError{}

// Validate checks the field values on JoinChatRoom with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *JoinChatRoom) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on JoinChatRoom with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in JoinChatRoomMultiError, or
// nil if none found.
func (m *JoinChatRoom) ValidateAll() error {
	return m.validate(true)
}

func (m *JoinChatRoom) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoomId

	if all {
		switch v := interface{}(m.GetMember()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, JoinChatRoomValidationError{
					field:  "Member",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, JoinChatRoomValidationError{
					field:  "Member",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMember()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return JoinChatRoomValidationError{
				field:  "Member",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return JoinChatRoomMultiError(errors)
	}

	return nil
}

// JoinChatRoomMultiError is an error wrapping multiple validation errors
// returned by JoinChatRoom.ValidateAll() if the designated constraints aren't met.
type JoinChatRoomMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m JoinChatRoomMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m JoinChatRoomMultiError) AllErrors() []error { return m }

// JoinChatRoomValidationError is the validation error returned by
// JoinChatRoom.Validate if the designated constraints aren't met.
type JoinChatRoomValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e JoinChatRoomValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e JoinChatRoomValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e JoinChatRoomValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e JoinChatRoomValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e JoinChatRoomValidationError) ErrorName() string { return "JoinChatRoomValidationError" }

// Error satisfies the builtin error interface
func (e JoinChatRoomValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sJoinChatRoom.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = JoinChatRoomValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = JoinChatRoomValidationError{}

// Validate checks the field values on LeaveChatRoom with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *LeaveChatRoom) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on LeaveChatRoom with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in LeaveChatRoomMultiError, or
// nil if none found.
func (m *LeaveChatRoom) ValidateAll() error {
	return m.validate(true)
}

func (m *LeaveChatRoom) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for RoomId

	if all {
		switch v := interface{}(m.GetMember()).(type) {
		case interface{ ValidateAll() error }:
			if err := v.ValidateAll(); err != nil {
				errors = append(errors, LeaveChatRoomValidationError{
					field:  "Member",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		case interface{ Validate() error }:
			if err := v.Validate(); err != nil {
				errors = append(errors, LeaveChatRoomValidationError{
					field:  "Member",
					reason: "embedded message failed validation",
					cause:  err,
				})
			}
		}
	} else if v, ok := interface{}(m.GetMember()).(interface{ Validate() error }); ok {
		if err := v.Validate(); err != nil {
			return LeaveChatRoomValidationError{
				field:  "Member",
				reason: "embedded message failed validation",
				cause:  err,
			}
		}
	}

	if len(errors) > 0 {
		return LeaveChatRoomMultiError(errors)
	}

	return nil
}

// LeaveChatRoomMultiError is an error wrapping multiple validation errors
// returned by LeaveChatRoom.ValidateAll() if the designated constraints
// aren't met.
type LeaveChatRoomMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m LeaveChatRoomMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m LeaveChatRoomMultiError) AllErrors() []error { return m }

// LeaveChatRoomValidationError is the validation error returned by
// LeaveChatRoom.Validate if the designated constraints aren't met.
type LeaveChatRoomValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e LeaveChatRoomValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e LeaveChatRoomValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e LeaveChatRoomValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e LeaveChatRoomValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e LeaveChatRoomValidationError) ErrorName() string { return "LeaveChatRoomValidationError" }

// Error satisfies the builtin error interface
func (e LeaveChatRoomValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sLeaveChatRoom.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = LeaveChatRoomValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = LeaveChatRoomValidationError{}

// Validate checks the field values on ChatRoomMember with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *ChatRoomMember) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on ChatRoomMember with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in ChatRoomMemberMultiError,
// or nil if none found.
func (m *ChatRoomMember) ValidateAll() error {
	return m.validate(true)
}

func (m *ChatRoomMember) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Uid

	// no validation rules for Username

	if len(errors) > 0 {
		return ChatRoomMemberMultiError(errors)
	}

	return nil
}

// ChatRoomMemberMultiError is an error wrapping multiple validation errors
// returned by ChatRoomMember.ValidateAll() if the designated constraints
// aren't met.
type ChatRoomMemberMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m ChatRoomMemberMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m ChatRoomMemberMultiError) AllErrors() []error { return m }

// ChatRoomMemberValidationError is the validation error returned by
// ChatRoomMember.Validate if the designated constraints aren't met.
type ChatRoomMemberValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e ChatRoomMemberValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e ChatRoomMemberValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e ChatRoomMemberValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e ChatRoomMemberValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e ChatRoomMemberValidationError) ErrorName() string { return "ChatRoomMemberValidationError" }

// Error satisfies the builtin error interface
func (e ChatRoomMemberValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sChatRoomMember.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = ChatRoomMemberValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = ChatRoomMemberValidationError{}

// Validate checks the field values on Content_Text with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content_Text) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Text with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Content_TextMultiError, or
// nil if none found.
func (m *Content_Text) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Text) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Content

	// no validation rules for Translated

	if len(errors) > 0 {
		return Content_TextMultiError(errors)
	}

	return nil
}

// Content_TextMultiError is an error wrapping multiple validation errors
// returned by Content_Text.ValidateAll() if the designated constraints aren't met.
type Content_TextMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_TextMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_TextMultiError) AllErrors() []error { return m }

// Content_TextValidationError is the validation error returned by
// Content_Text.Validate if the designated constraints aren't met.
type Content_TextValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_TextValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_TextValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_TextValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_TextValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_TextValidationError) ErrorName() string { return "Content_TextValidationError" }

// Error satisfies the builtin error interface
func (e Content_TextValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Text.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_TextValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_TextValidationError{}

// Validate checks the field values on Content_Image with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content_Image) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Image with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Content_ImageMultiError, or
// nil if none found.
func (m *Content_Image) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Image) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Caption

	// no validation rules for FileName

	// no validation rules for Format

	if len(errors) > 0 {
		return Content_ImageMultiError(errors)
	}

	return nil
}

// Content_ImageMultiError is an error wrapping multiple validation errors
// returned by Content_Image.ValidateAll() if the designated constraints
// aren't met.
type Content_ImageMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_ImageMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_ImageMultiError) AllErrors() []error { return m }

// Content_ImageValidationError is the validation error returned by
// Content_Image.Validate if the designated constraints aren't met.
type Content_ImageValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_ImageValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_ImageValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_ImageValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_ImageValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_ImageValidationError) ErrorName() string { return "Content_ImageValidationError" }

// Error satisfies the builtin error interface
func (e Content_ImageValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Image.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_ImageValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_ImageValidationError{}

// Validate checks the field values on Content_Video with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content_Video) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Video with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Content_VideoMultiError, or
// nil if none found.
func (m *Content_Video) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Video) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Caption

	// no validation rules for FileName

	// no validation rules for Format

	// no validation rules for CoverUrl

	if len(errors) > 0 {
		return Content_VideoMultiError(errors)
	}

	return nil
}

// Content_VideoMultiError is an error wrapping multiple validation errors
// returned by Content_Video.ValidateAll() if the designated constraints
// aren't met.
type Content_VideoMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_VideoMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_VideoMultiError) AllErrors() []error { return m }

// Content_VideoValidationError is the validation error returned by
// Content_Video.Validate if the designated constraints aren't met.
type Content_VideoValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_VideoValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_VideoValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_VideoValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_VideoValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_VideoValidationError) ErrorName() string { return "Content_VideoValidationError" }

// Error satisfies the builtin error interface
func (e Content_VideoValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Video.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_VideoValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_VideoValidationError{}

// Validate checks the field values on Content_Voice with the rules defined in
// the proto definition for this message. If any rules are violated, the first
// error encountered is returned, or nil if there are no violations.
func (m *Content_Voice) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Voice with the rules defined
// in the proto definition for this message. If any rules are violated, the
// result is a list of violation errors wrapped in Content_VoiceMultiError, or
// nil if none found.
func (m *Content_Voice) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Voice) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Caption

	// no validation rules for FileName

	// no validation rules for Format

	// no validation rules for Recognition

	if len(errors) > 0 {
		return Content_VoiceMultiError(errors)
	}

	return nil
}

// Content_VoiceMultiError is an error wrapping multiple validation errors
// returned by Content_Voice.ValidateAll() if the designated constraints
// aren't met.
type Content_VoiceMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_VoiceMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_VoiceMultiError) AllErrors() []error { return m }

// Content_VoiceValidationError is the validation error returned by
// Content_Voice.Validate if the designated constraints aren't met.
type Content_VoiceValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_VoiceValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_VoiceValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_VoiceValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_VoiceValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_VoiceValidationError) ErrorName() string { return "Content_VoiceValidationError" }

// Error satisfies the builtin error interface
func (e Content_VoiceValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Voice.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_VoiceValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_VoiceValidationError{}

// Validate checks the field values on Content_Document with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Content_Document) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Document with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Content_DocumentMultiError, or nil if none found.
func (m *Content_Document) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Document) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Url

	// no validation rules for Caption

	// no validation rules for FileName

	// no validation rules for Format

	if len(errors) > 0 {
		return Content_DocumentMultiError(errors)
	}

	return nil
}

// Content_DocumentMultiError is an error wrapping multiple validation errors
// returned by Content_Document.ValidateAll() if the designated constraints
// aren't met.
type Content_DocumentMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_DocumentMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_DocumentMultiError) AllErrors() []error { return m }

// Content_DocumentValidationError is the validation error returned by
// Content_Document.Validate if the designated constraints aren't met.
type Content_DocumentValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_DocumentValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_DocumentValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_DocumentValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_DocumentValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_DocumentValidationError) ErrorName() string { return "Content_DocumentValidationError" }

// Error satisfies the builtin error interface
func (e Content_DocumentValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Document.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_DocumentValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_DocumentValidationError{}

// Validate checks the field values on Content_Location with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *Content_Location) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on Content_Location with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// Content_LocationMultiError, or nil if none found.
func (m *Content_Location) ValidateAll() error {
	return m.validate(true)
}

func (m *Content_Location) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for X

	// no validation rules for Y

	// no validation rules for Scale

	// no validation rules for Label

	if len(errors) > 0 {
		return Content_LocationMultiError(errors)
	}

	return nil
}

// Content_LocationMultiError is an error wrapping multiple validation errors
// returned by Content_Location.ValidateAll() if the designated constraints
// aren't met.
type Content_LocationMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m Content_LocationMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m Content_LocationMultiError) AllErrors() []error { return m }

// Content_LocationValidationError is the validation error returned by
// Content_Location.Validate if the designated constraints aren't met.
type Content_LocationValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e Content_LocationValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e Content_LocationValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e Content_LocationValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e Content_LocationValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e Content_LocationValidationError) ErrorName() string { return "Content_LocationValidationError" }

// Error satisfies the builtin error interface
func (e Content_LocationValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sContent_Location.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = Content_LocationValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = Content_LocationValidationError{}
